### ISSUE TITLE
cholesteric-example broke after changing front to air

### ISSUE THREAD

**Issue by mysteriousHerb** [Berreman4x4/Berreman4x4#1]
Hello Olivier, 
Your code has been really essential to my current work in simulating a chiral nematic structure.
However, we have encountered a problem where the saturated reflectance became 0.9 with a strange decreasing of the intensity with wavelength. 

The problem happens when we set 

``` Python
# Materials
air = Berreman4x4.IsotropicNonDispersiveMaterial(1.0)
glass = Berreman4x4.IsotropicNonDispersiveMaterial(1.55)
front = Berreman4x4.IsotropicHalfSpace(air)
back = Berreman4x4.IsotropicHalfSpace(glass)
```

This is our experimental setup, where our chiral material is facing the air on top and glass slide at the bottom. 

![image](https://user-images.githubusercontent.com/13511170/37148676-34b0cc24-22c3-11e8-8150-447cb2e116d5.png)

**Comment by ocastany** [comment]
Hello,
I think my code is giving the right result in the case you mention. Using air instead of glass creates a reflection at the CLC interface, which has two consequences:
1. A direct reflection of the incident "R" wave, with inverted handedness -> increase of "R_LR".
2. The reflected "R" wave inside the CLC gets reflected backwards at the interface, with inverted handedness -> increase of "T_LR".

These two effects account for the reduced "R_RR" reflection coefficient. The slope of the curve is a feature often found with CLCs. Finally, note that an air/cholesteric interface is not realistic since air cannot provide horizontal alignment of the LC.
Olivier
